version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_SCHEDULE= 0 0 6 * * *
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_CLEANUP=true
      
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      - WATCHTOWER_NOTIFICATIONS=msteams
      - WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL=${WEBHOOK_TEAMS}
      - WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA=true
networks: 
  traefik:
    external: true